services:
  yolo-api:
    build: .
    image: lesson-22-docker-yolo-api:latest
    container_name: lesson_22_yolo_api
    ports:
      - "8000:8000"
    volumes:
      - ./outputs:/app/outputs
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
